name: ci
on: [ push, pull_request, workflow_dispatch ]

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22 ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
